/**
 * State Auto Insurance Data
 * Sourced from AUTO-INSURANCE-RESEARCH.md — 50 states + DC
 * Used by /car-accident-costs/ pages
 */

export interface StateAutoInsurance {
  stateCode: string;
  stateName: string;
  faultSystem: 'tort' | 'no-fault' | 'choice';
  minBiPerPerson: number;
  minBiPerAccident: number;
  minPd: number;
  pipRequired: boolean;
  pipMinimum: number | null;
  umRequired: boolean;
  medpayRequired: boolean;
  avgAnnualPremium: number | null;
  uninsuredRate: number | null;
  insuranceDeptUrl: string;
  insuranceDeptName: string;
  notes: string | null;
}

/**
 * Complete 50-state + DC auto insurance data
 * Sources: MoneyGeek, NerdWallet, NAIC, III, IRC (compiled April 2026)
 */
export const STATE_AUTO_INSURANCE: StateAutoInsurance[] = [
  { stateCode: 'AL', stateName: 'Alabama', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 1966, uninsuredRate: 18.0, insuranceDeptUrl: 'https://www.aldoi.gov/', insuranceDeptName: 'Alabama Dept. of Insurance', notes: null },
  { stateCode: 'AK', stateName: 'Alaska', faultSystem: 'tort', minBiPerPerson: 50000, minBiPerAccident: 100000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 1780, uninsuredRate: 9.8, insuranceDeptUrl: 'https://www.commerce.alaska.gov/web/ins/', insuranceDeptName: 'Alaska Division of Insurance', notes: null },
  { stateCode: 'AZ', stateName: 'Arizona', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 15000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2240, uninsuredRate: 11.8, insuranceDeptUrl: 'https://insurance.az.gov/', insuranceDeptName: 'Arizona Dept. of Insurance', notes: null },
  { stateCode: 'AR', stateName: 'Arkansas', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2120, uninsuredRate: 16.0, insuranceDeptUrl: 'https://insurance.arkansas.gov/', insuranceDeptName: 'Arkansas Insurance Dept.', notes: null },
  { stateCode: 'CA', stateName: 'California', faultSystem: 'tort', minBiPerPerson: 30000, minBiPerAccident: 60000, minPd: 15000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2398, uninsuredRate: 15.2, insuranceDeptUrl: 'https://www.insurance.ca.gov/', insuranceDeptName: 'California Dept. of Insurance', notes: 'Minimums increased Jan 1, 2025 — first increase since 1967' },
  { stateCode: 'CO', stateName: 'Colorado', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 15000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2430, uninsuredRate: 11.5, insuranceDeptUrl: 'https://doi.colorado.gov/', insuranceDeptName: 'Colorado Division of Insurance', notes: 'Collateral source rule is plaintiff-friendly — full billed amounts recoverable' },
  { stateCode: 'CT', stateName: 'Connecticut', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: true, medpayRequired: false, avgAnnualPremium: 2652, uninsuredRate: 9.4, insuranceDeptUrl: 'https://portal.ct.gov/CID', insuranceDeptName: 'Connecticut Insurance Dept.', notes: null },
  { stateCode: 'DE', stateName: 'Delaware', faultSystem: 'no-fault', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 10000, pipRequired: true, pipMinimum: 15000, umRequired: false, medpayRequired: false, avgAnnualPremium: 2580, uninsuredRate: 11.4, insuranceDeptUrl: 'https://insurance.delaware.gov/', insuranceDeptName: 'Delaware Dept. of Insurance', notes: 'PIP minimum: $15,000/$30,000 per person/per accident' },
  { stateCode: 'FL', stateName: 'Florida', faultSystem: 'no-fault', minBiPerPerson: 0, minBiPerAccident: 0, minPd: 10000, pipRequired: true, pipMinimum: 10000, umRequired: false, medpayRequired: false, avgAnnualPremium: 2878, uninsuredRate: 20.4, insuranceDeptUrl: 'https://www.myfloridacfo.com/division/consumers/', insuranceDeptName: 'Florida Office of Insurance Regulation', notes: 'PIP being REPEALED July 1, 2026 — shifting to $25K/$50K BI + $5K MedPay system' },
  { stateCode: 'GA', stateName: 'Georgia', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2340, uninsuredRate: 12.4, insuranceDeptUrl: 'https://oci.georgia.gov/', insuranceDeptName: 'Georgia Office of Insurance', notes: null },
  { stateCode: 'HI', stateName: 'Hawaii', faultSystem: 'no-fault', minBiPerPerson: 40000, minBiPerAccident: 80000, minPd: 20000, pipRequired: true, pipMinimum: 10000, umRequired: false, medpayRequired: false, avgAnnualPremium: 1636, uninsuredRate: 8.6, insuranceDeptUrl: 'https://cca.hawaii.gov/ins/', insuranceDeptName: 'Hawaii Insurance Division', notes: null },
  { stateCode: 'ID', stateName: 'Idaho', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 15000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 1548, uninsuredRate: 6.2, insuranceDeptUrl: 'https://doi.idaho.gov/', insuranceDeptName: 'Idaho Dept. of Insurance', notes: null },
  { stateCode: 'IL', stateName: 'Illinois', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 20000, pipRequired: false, pipMinimum: null, umRequired: true, medpayRequired: false, avgAnnualPremium: 2190, uninsuredRate: 12.3, insuranceDeptUrl: 'https://insurance.illinois.gov/', insuranceDeptName: 'Illinois Dept. of Insurance', notes: null },
  { stateCode: 'IN', stateName: 'Indiana', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: true, medpayRequired: false, avgAnnualPremium: 1860, uninsuredRate: 12.0, insuranceDeptUrl: 'https://www.in.gov/idoi/', insuranceDeptName: 'Indiana Dept. of Insurance', notes: null },
  { stateCode: 'IA', stateName: 'Iowa', faultSystem: 'tort', minBiPerPerson: 20000, minBiPerAccident: 40000, minPd: 15000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 1680, uninsuredRate: 8.7, insuranceDeptUrl: 'https://iid.iowa.gov/', insuranceDeptName: 'Iowa Insurance Division', notes: null },
  { stateCode: 'KS', stateName: 'Kansas', faultSystem: 'no-fault', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: true, pipMinimum: 4500, umRequired: true, medpayRequired: false, avgAnnualPremium: 2040, uninsuredRate: 9.9, insuranceDeptUrl: 'https://insurance.kansas.gov/', insuranceDeptName: 'Kansas Insurance Dept.', notes: null },
  { stateCode: 'KY', stateName: 'Kentucky', faultSystem: 'choice', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: true, pipMinimum: 10000, umRequired: false, medpayRequired: false, avgAnnualPremium: 2340, uninsuredRate: 13.4, insuranceDeptUrl: 'https://insurance.ky.gov/', insuranceDeptName: 'Kentucky Dept. of Insurance', notes: 'Choice state — drivers can opt out of no-fault and retain full lawsuit rights' },
  { stateCode: 'LA', stateName: 'Louisiana', faultSystem: 'tort', minBiPerPerson: 15000, minBiPerAccident: 30000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2883, uninsuredRate: 11.7, insuranceDeptUrl: 'https://www.ldi.la.gov/', insuranceDeptName: 'Louisiana Dept. of Insurance', notes: 'One of the lowest BI minimums and highest premiums in the nation' },
  { stateCode: 'ME', stateName: 'Maine', faultSystem: 'tort', minBiPerPerson: 50000, minBiPerAccident: 100000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: true, medpayRequired: true, avgAnnualPremium: 1175, uninsuredRate: 5.7, insuranceDeptUrl: 'https://www.maine.gov/pfr/insurance/', insuranceDeptName: 'Maine Bureau of Insurance', notes: 'Only state requiring MedPay (minimum $2,000/person). Lowest uninsured rate in nation.' },
  { stateCode: 'MD', stateName: 'Maryland', faultSystem: 'tort', minBiPerPerson: 30000, minBiPerAccident: 60000, minPd: 15000, pipRequired: true, pipMinimum: 2500, umRequired: true, medpayRequired: false, avgAnnualPremium: 2280, uninsuredRate: 12.2, insuranceDeptUrl: 'https://insurance.maryland.gov/', insuranceDeptName: 'Maryland Insurance Administration', notes: null },
  { stateCode: 'MA', stateName: 'Massachusetts', faultSystem: 'no-fault', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 30000, pipRequired: true, pipMinimum: 8000, umRequired: true, medpayRequired: false, avgAnnualPremium: 2100, uninsuredRate: 6.2, insuranceDeptUrl: 'https://www.mass.gov/orgs/division-of-insurance', insuranceDeptName: 'Massachusetts Division of Insurance', notes: null },
  { stateCode: 'MI', stateName: 'Michigan', faultSystem: 'no-fault', minBiPerPerson: 50000, minBiPerAccident: 100000, minPd: 10000, pipRequired: true, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2680, uninsuredRate: 19.6, insuranceDeptUrl: 'https://www.michigan.gov/difs', insuranceDeptName: 'Michigan DIFS', notes: 'PIP reformed in 2019 — previously unlimited; now tiered options available' },
  { stateCode: 'MN', stateName: 'Minnesota', faultSystem: 'no-fault', minBiPerPerson: 30000, minBiPerAccident: 60000, minPd: 10000, pipRequired: true, pipMinimum: 40000, umRequired: true, medpayRequired: false, avgAnnualPremium: 2070, uninsuredRate: 9.9, insuranceDeptUrl: 'https://mn.gov/commerce/insurance/', insuranceDeptName: 'Minnesota Dept. of Commerce', notes: 'Highest PIP minimum requirement in the nation ($40,000)' },
  { stateCode: 'MS', stateName: 'Mississippi', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2160, uninsuredRate: 28.2, insuranceDeptUrl: 'https://www.mid.ms.gov/', insuranceDeptName: 'Mississippi Insurance Dept.', notes: 'Highest uninsured driver rate in the nation (28.2%)' },
  { stateCode: 'MO', stateName: 'Missouri', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: true, medpayRequired: false, avgAnnualPremium: 2220, uninsuredRate: 14.0, insuranceDeptUrl: 'https://insurance.mo.gov/', insuranceDeptName: 'Missouri Dept. of Commerce & Insurance', notes: null },
  { stateCode: 'MT', stateName: 'Montana', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 20000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2040, uninsuredRate: 10.3, insuranceDeptUrl: 'https://csimt.gov/', insuranceDeptName: 'Montana CSI', notes: null },
  { stateCode: 'NE', stateName: 'Nebraska', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: true, medpayRequired: false, avgAnnualPremium: 1860, uninsuredRate: 8.6, insuranceDeptUrl: 'https://doi.nebraska.gov/', insuranceDeptName: 'Nebraska Dept. of Insurance', notes: null },
  { stateCode: 'NV', stateName: 'Nevada', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 20000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2820, uninsuredRate: 10.8, insuranceDeptUrl: 'https://doi.nv.gov/', insuranceDeptName: 'Nevada Division of Insurance', notes: 'Rates have approximately doubled year-over-year' },
  { stateCode: 'NH', stateName: 'New Hampshire', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 1560, uninsuredRate: 7.6, insuranceDeptUrl: 'https://www.nh.gov/insurance/', insuranceDeptName: 'New Hampshire Insurance Dept.', notes: 'Only state where auto insurance is not legally required (financial responsibility rules apply)' },
  { stateCode: 'NJ', stateName: 'New Jersey', faultSystem: 'choice', minBiPerPerson: 35000, minBiPerAccident: 70000, minPd: 25000, pipRequired: true, pipMinimum: 15000, umRequired: true, medpayRequired: false, avgAnnualPremium: 2580, uninsuredRate: 14.9, insuranceDeptUrl: 'https://www.state.nj.us/dobi/', insuranceDeptName: 'New Jersey DOBI', notes: 'Choice state. BI minimums increased to 35/70 effective Jan 1, 2026' },
  { stateCode: 'NM', stateName: 'New Mexico', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 10000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2100, uninsuredRate: 24.9, insuranceDeptUrl: 'https://www.osi.state.nm.us/', insuranceDeptName: 'New Mexico Office of Superintendent of Insurance', notes: 'Second-highest uninsured driver rate (24.9%)' },
  { stateCode: 'NY', stateName: 'New York', faultSystem: 'no-fault', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 10000, pipRequired: true, pipMinimum: 50000, umRequired: true, medpayRequired: false, avgAnnualPremium: 2760, uninsuredRate: 6.1, insuranceDeptUrl: 'https://www.dfs.ny.gov/', insuranceDeptName: 'New York Dept. of Financial Services', notes: 'Highest PIP dollar minimum ($50,000)' },
  { stateCode: 'NC', stateName: 'North Carolina', faultSystem: 'tort', minBiPerPerson: 50000, minBiPerAccident: 100000, minPd: 50000, pipRequired: false, pipMinimum: null, umRequired: true, medpayRequired: false, avgAnnualPremium: 1920, uninsuredRate: 7.4, insuranceDeptUrl: 'https://www.ncdoi.gov/', insuranceDeptName: 'North Carolina DOI', notes: 'Minimums increased to 50/100/50 effective Jan 1, 2025' },
  { stateCode: 'ND', stateName: 'North Dakota', faultSystem: 'no-fault', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: true, pipMinimum: 30000, umRequired: true, medpayRequired: false, avgAnnualPremium: 1680, uninsuredRate: 7.2, insuranceDeptUrl: 'https://www.insurance.nd.gov/', insuranceDeptName: 'North Dakota Insurance Dept.', notes: null },
  { stateCode: 'OH', stateName: 'Ohio', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 1740, uninsuredRate: 12.0, insuranceDeptUrl: 'https://insurance.ohio.gov/', insuranceDeptName: 'Ohio Dept. of Insurance', notes: null },
  { stateCode: 'OK', stateName: 'Oklahoma', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2280, uninsuredRate: 14.6, insuranceDeptUrl: 'https://www.oid.ok.gov/', insuranceDeptName: 'Oklahoma Insurance Dept.', notes: null },
  { stateCode: 'OR', stateName: 'Oregon', faultSystem: 'no-fault', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 20000, pipRequired: true, pipMinimum: 15000, umRequired: true, medpayRequired: false, avgAnnualPremium: 2040, uninsuredRate: 11.4, insuranceDeptUrl: 'https://dfr.oregon.gov/', insuranceDeptName: 'Oregon Division of Financial Regulation', notes: null },
  { stateCode: 'PA', stateName: 'Pennsylvania', faultSystem: 'choice', minBiPerPerson: 15000, minBiPerAccident: 30000, minPd: 5000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2280, uninsuredRate: 7.6, insuranceDeptUrl: 'https://www.insurance.pa.gov/', insuranceDeptName: 'Pennsylvania Insurance Dept.', notes: 'Choice state — lowest BI minimums in nation (15/30). Drivers choose between limited tort and full tort.' },
  { stateCode: 'RI', stateName: 'Rhode Island', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2340, uninsuredRate: 10.8, insuranceDeptUrl: 'https://dbr.ri.gov/', insuranceDeptName: 'Rhode Island DBR', notes: null },
  { stateCode: 'SC', stateName: 'South Carolina', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: true, medpayRequired: false, avgAnnualPremium: 2280, uninsuredRate: 9.9, insuranceDeptUrl: 'https://doi.sc.gov/', insuranceDeptName: 'South Carolina DOI', notes: null },
  { stateCode: 'SD', stateName: 'South Dakota', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: true, medpayRequired: false, avgAnnualPremium: 1800, uninsuredRate: 8.2, insuranceDeptUrl: 'https://dlr.sd.gov/insurance/', insuranceDeptName: 'South Dakota Division of Insurance', notes: null },
  { stateCode: 'TN', stateName: 'Tennessee', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2160, uninsuredRate: 20.9, insuranceDeptUrl: 'https://www.tn.gov/commerce/insurance.html', insuranceDeptName: 'Tennessee Dept. of Commerce & Insurance', notes: 'Fourth-highest uninsured driver rate (20.9%)' },
  { stateCode: 'TX', stateName: 'Texas', faultSystem: 'tort', minBiPerPerson: 30000, minBiPerAccident: 60000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2400, uninsuredRate: 14.1, insuranceDeptUrl: 'https://www.tdi.texas.gov/', insuranceDeptName: 'Texas Dept. of Insurance', notes: null },
  { stateCode: 'UT', stateName: 'Utah', faultSystem: 'no-fault', minBiPerPerson: 30000, minBiPerAccident: 65000, minPd: 25000, pipRequired: true, pipMinimum: 3000, umRequired: false, medpayRequired: false, avgAnnualPremium: 2160, uninsuredRate: 8.2, insuranceDeptUrl: 'https://insurance.utah.gov/', insuranceDeptName: 'Utah Insurance Dept.', notes: 'Lowest PIP minimum ($3,000). BI minimums increased Jan 1, 2025' },
  { stateCode: 'VT', stateName: 'Vermont', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 10000, pipRequired: false, pipMinimum: null, umRequired: true, medpayRequired: false, avgAnnualPremium: 1536, uninsuredRate: 7.0, insuranceDeptUrl: 'https://dfr.vermont.gov/', insuranceDeptName: 'Vermont Dept. of Financial Regulation', notes: null },
  { stateCode: 'VA', stateName: 'Virginia', faultSystem: 'tort', minBiPerPerson: 50000, minBiPerAccident: 100000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2040, uninsuredRate: 9.9, insuranceDeptUrl: 'https://www.scc.virginia.gov/pages/Bureau-of-Insurance', insuranceDeptName: 'Virginia Bureau of Insurance', notes: 'Minimums increased to 50/100/25 effective Jan 1, 2025' },
  { stateCode: 'WA', stateName: 'Washington', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 10000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 2040, uninsuredRate: 15.2, insuranceDeptUrl: 'https://www.insurance.wa.gov/', insuranceDeptName: 'Washington Office of Insurance Commissioner', notes: null },
  { stateCode: 'DC', stateName: 'District of Columbia', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 10000, pipRequired: false, pipMinimum: null, umRequired: true, medpayRequired: false, avgAnnualPremium: 4017, uninsuredRate: 25.2, insuranceDeptUrl: 'https://disb.dc.gov/', insuranceDeptName: 'DC Dept. of Insurance, Securities & Banking', notes: 'Highest average premium in the nation ($4,017/yr). Third-highest uninsured rate (25.2%)' },
  { stateCode: 'WV', stateName: 'West Virginia', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 25000, pipRequired: false, pipMinimum: null, umRequired: true, medpayRequired: false, avgAnnualPremium: 2100, uninsuredRate: 9.3, insuranceDeptUrl: 'https://www.wvinsurance.gov/', insuranceDeptName: 'West Virginia Offices of Insurance Commissioner', notes: null },
  { stateCode: 'WI', stateName: 'Wisconsin', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 10000, pipRequired: false, pipMinimum: null, umRequired: true, medpayRequired: false, avgAnnualPremium: 1620, uninsuredRate: 12.4, insuranceDeptUrl: 'https://oci.wi.gov/', insuranceDeptName: 'Wisconsin Office of Commissioner of Insurance', notes: null },
  { stateCode: 'WY', stateName: 'Wyoming', faultSystem: 'tort', minBiPerPerson: 25000, minBiPerAccident: 50000, minPd: 20000, pipRequired: false, pipMinimum: null, umRequired: false, medpayRequired: false, avgAnnualPremium: 1860, uninsuredRate: 5.9, insuranceDeptUrl: 'https://doi.wyo.gov/', insuranceDeptName: 'Wyoming Dept. of Insurance', notes: 'Second-lowest uninsured rate in nation (5.9%)' },
];

export function getStateInsurance(stateCode: string): StateAutoInsurance | undefined {
  return STATE_AUTO_INSURANCE.find(s => s.stateCode === stateCode.toUpperCase());
}

export function getStateSlug(stateName: string): string {
  return stateName.toLowerCase().replace(/\s+/g, '-');
}

export function getStateBySlug(slug: string): StateAutoInsurance | undefined {
  return STATE_AUTO_INSURANCE.find(s => getStateSlug(s.stateName) === slug);
}

export function formatBiLimits(perPerson: number, perAccident: number): string {
  if (perPerson === 0 && perAccident === 0) return 'None required';
  return `$${(perPerson / 1000).toFixed(0)}K / $${(perAccident / 1000).toFixed(0)}K`;
}

export function faultSystemLabel(system: string): string {
  switch (system) {
    case 'no-fault': return 'No-Fault';
    case 'choice': return 'Choice (No-Fault or Tort)';
    case 'tort': return 'At-Fault (Tort)';
    default: return system;
  }
}
